name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      # Add a step to build the Docker containers (optional)
      - name: Build Containers
        run: docker-compose build

      - name: Check
        run: docker-compose run --rm app sh -c "python manage.py check"

      # Run your existing test command
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Add a step to print logs from the db container
      - name: Print Database Logs
        run: docker-compose logs db

      # Run your existing lint command
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
